# Generated by Django 3.2.5 on 2021-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('blood_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, max_length=400, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('Hh', 'Hh')], default=None, max_length=20)),
                ('blood_type', models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default=None, max_length=50)),
                ('acceptable_blood_group', models.CharField(max_length=100)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('units', models.CharField(max_length=5)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('hospital_initials', models.CharField(default='KMC', max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'Blood Request',
            },
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('date_of_birth', models.CharField(default='', max_length=11)),
                ('email_id', models.EmailField(max_length=200)),
                ('phone', models.CharField(default='', max_length=11)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.BooleanField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Pondicherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')])),
                ('weight', models.CharField(default='', max_length=10)),
                ('agree', models.BooleanField(blank=True, default=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('Hh', 'Hh')], default=None, max_length=4)),
            ],
        ),
    ]
