# Generated by Django 3.2.5 on 2021-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='custom_field_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='custom_field_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
