# Generated by Django 3.2.5 on 2021-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='pin_code',
            field=models.IntegerField(default=False),
        ),
    ]
