# Generated by Django 3.2.5 on 2021-07-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='acceptable_blood_group',
        ),
    ]
