# Generated by Django 3.2.5 on 2021-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_initials',
            field=models.CharField(default='K', max_length=50),
        ),
    ]
