# Generated by Django 3.2.5 on 2021-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bloodrequest_hospital_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_initials',
            field=models.CharField(default='KMC', max_length=50),
        ),
    ]
