# Generated by Django 3.2.5 on 2021-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bloodrequest_acceptable_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='acceptable_blood_group',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
