# Generated by Django 3.2.5 on 2021-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210903_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
