# Generated by Django 3.2.5 on 2021-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donorrequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
