# Generated by Django 3.2.5 on 2021-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bloodrequest_hospital_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
