# Generated by Django 3.2.5 on 2021-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210924_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='designation',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
