# Generated by Django 3.2.5 on 2021-08-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_donorrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
