# Generated by Django 3.2.5 on 2021-08-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_donorrequest_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorrequest',
            old_name='agree',
            new_name='I_agree_to_the_terms_and_conditions_stated_below',
        ),
    ]
