# Generated by Django 3.2.5 on 2021-09-25 15:17

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_donorrequest_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=home.models.upload_review_photo),
        ),
    ]
