# Generated by Django 3.2.5 on 2021-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bloodrequest_acceptable_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='note',
            field=models.TextField(blank=True, default=None),
        ),
    ]
