# Generated by Django 3.2.5 on 2021-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_donorrequest_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='I_agree_to_the_terms_and_conditions_stated_below',
            field=models.BooleanField(default=True),
        ),
    ]
