# Generated by Django 3.2.5 on 2021-09-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_donorrequest_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='', max_length=160)),
                ('state_id', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='city',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='home.cities'),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='state',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='home.states'),
        ),
    ]
