# Generated by Django 3.2.5 on 2021-09-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210926_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='state_id',
            field=models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='home.states'),
        ),
    ]
