# Generated by Django 3.2.5 on 2021-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_donorrequest_i_agree_to_the_terms_and_conditions_stated_below'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='acceptable_blood_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('Hh', 'Hh')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('Whole Blood', 'Whole Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_initials',
            field=models.CharField(default='', max_length=50),
        ),
    ]
