# Generated by Django 3.2.5 on 2021-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cities_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='id',
            new_name='city_id',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='state_id',
        ),
        migrations.AddField(
            model_name='cities',
            name='city_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
