# Generated by Django 3.2.5 on 2021-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210827_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='urgent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
