# Generated by Django 3.2.5 on 2021-07-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_bloodrequest_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='note',
        ),
    ]
