# Generated by Django 3.2.5 on 2021-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_bloodrequest_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='urgent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
