# Generated by Django 3.2.5 on 2021-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bloodrequest_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorrequest',
            name='pin_code',
        ),
    ]
