# Generated by Django 3.2.5 on 2021-07-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_bloodrequest_acceptable_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='Phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
