# Generated by Django 3.2.5 on 2021-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_donorrequest_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='pin_code',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, default=False),
        ),
    ]
