# Generated by Django 3.2.5 on 2021-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210827_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='date_of_birth',
            field=models.DateField(default=False),
        ),
    ]
