# Generated by Django 3.2.5 on 2021-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_bloodrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='acceptable_blood_group',
            field=models.CharField(max_length=100),
        ),
    ]
