# Generated by Django 3.2.5 on 2021-08-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20210831_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmessage',
            old_name='title',
            new_name='subject',
        ),
    ]
