# Generated by Django 3.2.5 on 2021-08-27 20:15

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=False, max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=250)),
                ('content', models.TextField(default=False)),
                ('image', models.FileField(blank=True, default=False, upload_to=blog.models.upload_location)),
                ('section', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
