# Generated by Django 3.2.5 on 2021-08-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontent',
            old_name='subtitle',
            new_name='subheading',
        ),
    ]
