# Generated by Django 3.2.5 on 2021-09-03 06:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='caption_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='images',
            field=models.ImageField(blank=True, default=None, upload_to=blog.models.upload_here),
        ),
    ]
