# Generated by Django 3.2.5 on 2021-08-27 20:18

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_subtitle_blogcontent_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=blog.models.upload_location),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
