# Generated by Django 3.2.5 on 2021-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210807_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedIn',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
